# Generated by Django 5.1.3 on 2024-12-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='company',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
